### ISSUE TITLE
Memory keeps increasing and stacking up upon displaying and closing the camera preview multiple times

### ISSUE THREAD

**Issue by GabrielAraujo** [Apparence-io/CamerAwesome#242] opened 2023-02-06 14:05 UTC
## Steps to Reproduce

If you keep displaying and closing the camera multiple times it will increase the RAM usage to a point where the app crashes due to OOM.
![Screen Shot 2023-02-06 at 11 00 58](https://user-images.githubusercontent.com/7611463/216991155-df42e9ca-049a-404a-a8e0-a7a417ec1083.png)

As you can see in the image the spike is when you open the camera and when it drops upon closing it never comes back to the previous level of mem usage. And it is because of some memory retain that is happening on the call tree bellow
![Screen Shot 2023-02-06 at 11 02 29](https://user-images.githubusercontent.com/7611463/216991517-e00267d4-25f6-4005-8224-05aee2ab901b.png)

I've found [this thread](https://github.com/flutter/flutter/issues/77621) but I don't know if it relates to how the plugin was implemented.

Due to the nature of our app, the users open and close the camera quite a lot and OOM issues is the main cause of crashes for us right now.

## Expected results

App running smoothly

## Actual results

App crashing

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone X*  | *13.6.1*  |

</details>

**Comment by g-apparence** [comment] 2023-02-06 15:18
Thank you for this great analyze. 
We will investigate further to reproduce and see what we can do.

**Comment by GabrielAraujo** [comment] 2023-02-06 17:04
@g-apparence Thank you! I've also tested under the example project on this repo and the same happens.. So it is def something related to how we display the camera preview on the native side.

Let me know if you need any help!

![Screen Shot 2023-02-06 at 14 03 03](https://user-images.githubusercontent.com/7611463/217036577-331a2193-f2d5-4187-896c-ee23485f3bc7.png)

**Comment by jamesdixon** [comment] 2023-02-06 17:58
@GabrielAraujo nice find!

**Comment by g-apparence** [comment] 2023-02-07 14:14
Checked on Android 
Seems ok
![Capture d’écran 2023-02-07 à 15 13 04](https://user-images.githubusercontent.com/48241546/217268797-301090e0-91e3-461d-8d21-3189009c1352.png)

Going to try reproducing on some iOS phones now. 
I'll let you know

**Comment by g-apparence** [comment] 2023-02-07 14:40
> @g-apparence Thank you! I've also tested under the example project on this repo and the same happens.. So it is def something related to how we display the camera preview on the native side.
> 
> Let me know if you need any help!
> 
> ![Screen Shot 2023-02-06 at 14 03 03](https://user-images.githubusercontent.com/7611463/217036577-331a2193-f2d5-4187-896c-ee23485f3bc7.png)

Seems related yes... 
This seems like a big flutter issue that should get more attention

**Comment by GabrielAraujo** [comment] 2023-02-07 14:54
I've tested using the Camera from the Image picker package and the same does not happen.. Could it be something this package is not properly handling/disposing? Due to the not released mem size it feels like it is some kind of image buffer that is not properly released..

Do you have any next steps in mind or are you planning on waiting for the flutter side?

**Comment by jamesdixon** [comment] 2023-02-07 15:22
@g-apparence is there a specific Flutter issue on Github that you're referencing?

**Comment by g-apparence** [comment] 2023-02-07 15:26
From the initial message
> I've found https://github.com/flutter/flutter/issues/77621

I've some ideas, but I have to discuss first with our iOS expert as I'm not comfortable with ObjC.

**Comment by g-apparence** [comment] 2023-02-08 09:21
I can't reproduce this on an Iphone X / iOS 16.3.
- What is your flutter version? (I've stayed on the previous flutter version). 
- what is the camerAwesome version you used? 
- Did you run this test in profile mode? 

Maybe that's related to pre iOS 16 and textures. 
I've added an unregister texture before closing the videoon iOS, but I cannot garantee that's going to fix your bug.

**Comment by GabrielAraujo** [comment] 2023-02-08 10:59
- What is your flutter version? (I've stayed on the previous flutter version).
**I've used the version 3.3.10 and also the 3.7.0 both with the same problems**

- what is the camerAwesome version you used?
**I've tested with the 0.3.3 version and also with the 1.2.0, both showed the same results**

- Did you run this test in profile mode?
**Yes, I've also tested on my iphone 13 Pro on profile with iOS 16 and it also occurs** 

![Screen Shot 2023-02-08 at 07 52 30](https://user-images.githubusercontent.com/7611463/217510664-92a1ea50-1121-4e5a-8c1a-73bcacebea90.png)
Even seems to be a bit worst and the memory don't return to a lower level at all.

[Here](https://gist.github.com/GabrielAraujo/86ad8f9024216bc5bafc09a6ae684cef) is the gist on the changes I did on `main.dart` for the example project so we could simulate closing/reopening the camera. (Could also be something on the way I've implemented it too)

**Comment by GabrielAraujo** [comment] 2023-02-08 11:09
The good news is that on the Fix you worked on it seems to solve the issue:
![Screen Shot 2023-02-08 at 08 08 22](https://user-images.githubusercontent.com/7611463/217513247-8c886f3d-1a04-4f8e-bce9-9126075c1698.png)

Here is the mem profile after opening/closing the camera multiple times

**Comment by g-apparence** [comment] 2023-02-08 12:46
Ahh great. 

I think it's related on the fact that you are using a constant Key on the camera page.
Flutter tries to recreate the same widget without the texture properly disposed. 
Just out of curiosity, I'll try to see if that's right.

**Comment by g-apparence** [comment] 2023-02-08 12:48
I close this as it seems fixed. 
Thank you for your help fixing this. 🙏🏻

**Closed by g-apparence** 2023-02-08 12:48 UTC
Labels: bug, iOS, priority 1

**Comment by jnarowski** [comment] 2023-02-08 21:58
Thank you for fixing this! Do you have an idea when this will be released as an official version increment to the package?
