### ISSUE TITLE
Front camera and back camera cannot work together

### ISSUE THREAD

**Issue by dvird** [Apparence-io/CamerAwesome#151] opened 2022-10-11 10:39 UTC
Front camera and back  camera cannot work together
Like bereal
![thumb_Screen Shot 2022-10-08 at 19 35 36](https://user-images.githubusercontent.com/42498461/195068931-dc91e5dd-cc94-48bb-ab7f-5375364b0df9.png)

## Steps to Reproduce

*Describe how to reproduce the error*

## Expected results

*What it should be*

## Actual results

only front or only back. its not working together

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone X*  | *13.6.1*  |

</details>

**Comment by g-apparence** [comment] 2022-10-14 15:26
Thank you reporting this. 
I'm not sure anymore but there was a technical reason when we did this. 

(ps: I renamed your issue title as you've put the url of this page)

**Comment by aytunch** [comment] 2022-10-14 18:33
@g-apparence In this thread you can find the native APIs which will allow this functionality.
I beleive that this feature would be an awesome addition to this awesome plugin 🗡️:D
https://github.com/flutter/flutter/issues/51928#issuecomment-1120289524

**Comment by istornz** [comment] 2023-01-10 14:42
Closed because duplicate of #131

**Closed by istornz** 2023-01-10 14:42 UTC
Labels: enhancement, android, iOS
