### ISSUE TITLE
ai analysis faces crash 

### ISSUE THREAD

**Issue by miguelflores1993** [Apparence-io/CamerAwesome#230] opened 2023-01-30 13:33 UTC
PHONE MODEL : Xiaomi 11 T android 12
I run the project, it opens fine, but after about 40 seconds, the application closes and that image error appears.

![Screenshot_2023-01-30-09-28-35-673_com miui bugreport](https://user-images.githubusercontent.com/67565934/215491430-2d4386f9-bcce-419e-8f16-339808b395de.jpg)

**Comment by apalala-dev** [comment] 2023-01-30 13:58
Can you specify your `CamerAwesomeBuilder` config so we can try to reproduce it please ?

In ai_analysis_faces.dart for example, it would be:
``` dart
CameraAwesomeBuilder.awesome(
  saveConfig: SaveConfig.photoAndVideo(
    photoPathBuilder: () => path(CaptureMode.photo),
    videoPathBuilder: () => path(CaptureMode.video),
    initialCaptureMode: CaptureMode.photo,
  ),
  onMediaTap: (mediaCapture) => OpenFile.open(mediaCapture.filePath),
  previewFit: CameraPreviewFit.contain,
  aspectRatio: CameraAspectRatios.ratio_1_1,
  sensor: Sensors.front,
  onImageForAnalysis: (img) => _analyzeImage(img),
  imageAnalysisConfig: AnalysisConfig(
    outputFormat: InputAnalysisImageFormat.nv21,
    width: 250,
    maxFramesPerSecond: 30,
  ),
  previewDecoratorBuilder: (state, previewSize, previewRect) {
    return _MyPreviewDecoratorWidget(
      cameraState: state,
      faceDetectionStream: _faceDetectionController,
      previewSize: previewSize,
      previewRect: previewRect,
    );
  },
)
```

The `AnalysisConfig` is the most important part.

**Comment by g-apparence** [comment] 2023-01-30 14:25
Please also specify the flutter version you used. 👌

**Comment by miguelflores1993** [comment] 2023-01-30 15:39
I am using the example project, I am using the code file called 
`ai_analysis_faces.dart`

`version flutter 3.3.10`

**Comment by miguelflores1993** [comment] 2023-01-30 15:45
@apalala-dev @g-apparence 
I would like to know if you can customize the box that focuses on the face, is it possible?

![image](https://user-images.githubusercontent.com/67565934/215524007-0e77011e-9864-4f48-8636-c01a809f16fd.png)

**Comment by apalala-dev** [comment] 2023-01-30 16:39
I will try to reproduce your Out of memory error. Where you using a lot of apps at the same time maybe?
Does it reproduce every time you try it?

About the box around the faces, do you just want to place the square around the face ?
- This should be doable quite easily since MLKit gives the area on which a face has been found.

If you want to focus on the entire face instead of a single point, it's not possible atm with CamerAwesome.
We might add this feature some day but can't promise as there are other areas that already need more work.

**Comment by miguelflores1993** [comment] 2023-01-30 19:54
Yes exactly, this happens every time I corrode the app, I don't think my phone is 8 GB RAM, and I try to close all apps at this time, and I have the same problem, maybe it's the phone model?

maybe a quick example to do something like that? I don't have much experience in painting

> Intentaré reproducir su error de falta de memoria. ¿Quizás estás usando muchas aplicaciones al mismo tiempo? ¿Se reproduce cada vez que lo pruebas?
> 
> Sobre el cuadro alrededor de las caras, ¿solo quieres colocar el cuadrado alrededor de la cara?
> 
> * Esto debería ser factible con bastante facilidad ya que MLKit proporciona el área en la que se ha encontrado una cara.
> 
> Si desea enfocarse en todo el rostro en lugar de en un solo punto, no es posible hacerlo con CamerAwesome. Es posible que agreguemos esta característica algún día, pero no podemos prometer que hay otras áreas que ya necesitan más trabajo.

**Comment by apalala-dev** [comment] 2023-01-31 08:25
Maybe, I am not sure. I was never able to reproduce this problem even on a Xiaomi Mi 9T (which is 3 years old now). I often let the app run for ~10 minutes and I don't get any error.
I will take a look on an emulator, it might be related to the Android version.

A similar CustomPaint is used for the [focus indicator](https://github.com/Apparence-io/CamerAwesome/blob/master/lib/src/layouts/awesome/widgets/awesome_focus_indicator.dart).

MLKit provides a property `boundingBox` which is a `Rect` around the face it detects.
In `ai_analysis_faces.dart`, you can find this property in the `face` variable ([line 298](https://github.com/Apparence-io/CamerAwesome/blob/4022a571693b8639e6b50d131ec499c496e81c78/example/lib/ai_analysis_faces.dart#L298)).
Once you get the rect, you just have to draw the face (similar to the focus indicator) around it.
An other option if you are really not confident with `CustomPaint` is to just draw a picture (jpeg, svg...) or a widget placed in that rectangle. You could use `face.boundingBox.center` to get the center of the `Rect` to help you place it correctly.

**Comment by apalala-dev** [comment] 2023-01-31 08:42
I have been able to reproduce the issue.
Memory usage seems to be growing indefinitely until it crashes. There is probably a memory leak somewhere, I will try to find it and let you updated!

**Comment by apalala-dev** [comment] 2023-01-31 09:08
It seems to be related to MLKit and not CamerAwesome itself.
When commenting the line that makes the processing (`faceDetector.processImage(inputImage)`), the memory stop growing endlessly.
I think that it depends on devices, but if you are struggling with this kind of issues, you can reduce the `maxFramesPerSecond` of CamerAwesome in `AnalysisConfig`. With a 10 images limit instead of 30, it did not grow endlessly anymore as it did before.

**Comment by miguelflores1993** [comment] 2023-01-31 12:27
Thanks, I imagine they will correct this problem?

**Comment by apalala-dev** [comment] 2023-01-31 12:38
I guess, but I am not 100% sure.
Image analysis is an heavy work and might not behave the same way depending on the device it runs on.
You should probably try what maxFramesPerSecond and resolution work for your app on a low-end device then adapt these numbers based on device capabilities.

I'll close this issue since it's not related to CamerAwesome, but feel free to open a new one if you encounter an other problem.

**Closed by apalala-dev** 2023-01-31 12:38 UTC
