### ISSUE TITLE
The dependency package on the M1 chip MAC is always in get state

### ISSUE THREAD

**Issue by llmmirror** [Apparence-io/CamerAwesome#309] opened 2023-04-07 06:23 UTC
flutter pub get
Running "flutter pub get" in ts ... It went on like this for dozens of minutes

But libraries like camera can be downloaded quickly

**Comment by g-apparence** [comment] 2023-04-07 06:27
Sorry we are not understanding. 
please do write an understandable issue that we can reproduce and understand.
Only english is allowed here, thank you.

Please also provide if possible
- reproductible code 
- scenario
- what you expect

**Comment by tsanyqudsi** [comment] 2023-04-07 15:26
I think the issue is not from the package, but it's from other stuff.

Do you think you have the same issue like this ? https://github.com/flutter/flutter/issues/82436

**Comment by g-apparence** [comment] 2023-06-07 07:03
That's a bug with flutter. 
I close this.

**Closed by g-apparence** 2023-06-07 07:03 UTC
